on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

name: Build Docker images

jobs:
  get-tag:
    runs-on: ubuntu-latest
    outputs:
      previous-tag: ${{ steps.previoustag.outputs.tag }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - run: git fetch --tags origin

      - name: Get latest tag on repo
        id: previoustag
        uses: WyriHaximus/github-action-get-previous-tag@v1

  build-docker:
    needs: get-tag
    name: Build Docker image ${{ needs.get-tag.outputs.previous-tag }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ needs.get-tag.outputs.previous-tag }}

      - name: Set up QEMU for cross-compilation
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Acquire Docker image metadata
        id: metadata
        uses: docker/metadata-action@v4
        with:
          images: florianpiesche/sonic
          tags: |
            ${{ needs.get-tag.outputs.previous-tag }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image ${{ needs.get-tag.outputs.previous-tag }}
        uses: docker/build-push-action@v4
        id: build
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          push: true
